config/routes.rb
Dinnertyme::Application.routes.draw do
  
  match '/home' => 'home#index', :via => :get
  match '/about' => 'home#about', :via => :get
  match '/faq' => 'home#faq', :via => :get 

  resources :ingredients

  resources :recipes

  resources :kitchens

root :to => 'home#index'

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  unit       :string(255)
#  amount     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :amount, :name, :unit, :recipe_ids
  has_and_belongs_to_many :recipes
end

app/models/kitchen.rb
# == Schema Information
#
# Table name: kitchens
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Kitchen < ActiveRecord::Base
  attr_accessible :name, :recipe_ids
  has_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  steps      :text
#  photo      :string(255)
#  serves     :integer
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kitchen_id :integer
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :photo, :rating, :serves, :steps, :kitchen_id, :ingredient_ids
  belongs_to :kitchen
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end
	
	def about
		
	end
	
	def faq
		
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchens = Kitchen.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kitchens }
    end
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/new
  # GET /kitchens/new.json
  def new
    @kitchen = Kitchen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/1/edit
  def edit
    @kitchen = Kitchen.find(params[:id])
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(params[:kitchen])

    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully created.' }
        format.json { render json: @kitchen, status: :created, location: @kitchen }
      else
        format.html { render action: "new" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kitchens/1
  # PUT /kitchens/1.json
  def update
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      if @kitchen.update_attributes(params[:kitchen])
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    @kitchen = Kitchen.find(params[:id])
    @kitchen.destroy

    respond_to do |format|
      format.html { redirect_to kitchens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<div class="row">
    <div class="span9">
        <div class="hero-unit">
            	<h1>Welcome to DinnerTyme!</h1>
        </div>
    </div>
        <div class="row">
            <div class="span9">
                <span>DinnerTyme is an application that helps you figure out what to have for dinner tonight based on the inventory in your kitchen</span>
            </div>
            <br>
            <div class="span9">
            	<div><h2>Which Kitchen are you in?</h2></div>
            	
            	<% Kitchen.all.each do |kitchen|%>
            	<div class="btn btn-large">
            	<%= link_to kitchen.name, kitchen_path(kitchen)%>
            	</div>
            	<%end%>
                <div class="btn btn-large">
                <%= link_to 'New Kitchen', new_kitchen_path%>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Unit</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr class="ingredient">
    <td><%= ingredient.name %></td>
    <td><%= ingredient.unit %></td>
    <td><%= ingredient.amount %></td>
    
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Remove', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
  </tr>
<% end %>
</table>

<br />

<div class="btn btn-large btn-success"><%= link_to 'New Ingredient', new_ingredient_path %></div>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ingredient.name %>
</p>

<p>
  <b>Unit:</b>
  <%= @ingredient.unit %>
</p>

<p>
  <b>Amount:</b>
  <%= @ingredient.amount %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/kitchens/_form.html.erb
<%= form_for(@kitchen) do |f| %>
  <% if @kitchen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitchen.errors.count, "error") %> prohibited this kitchen from being saved:</h2>

      <ul>
      <% @kitchen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitchens/edit.html.erb
<h1>Editing kitchen</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitchen %> |
<%= link_to 'Back', kitchens_path %>

app/views/kitchens/index.html.erb
<h1>All Your Kitchens</h1>

<% @kitchens.each do |kitchen| %>
    <div class="btn btn-large kitchen"><%= link_to kitchen.name, kitchen_path(kitchen) %></div>


<% end %>
<br>
<div class="btn btn-large btn-success kitchen"><%= link_to 'New Kitchen', new_kitchen_path %></div>

app/views/kitchens/new.html.erb
<h1>New kitchen</h1>

<%= render 'form' %>

<%= link_to 'Back', kitchens_path %>

app/views/kitchens/show.html.erb
<div>
    <h1><%=@kitchen.name%></h1>
</div>
<div>
    <p>What do you want to eat? Select a recipe below.</p>
</div>   
        <div>
            <h2>Recipes</h2>
        </div>            	
        <% @kitchen.recipes.all.each do |recipe|%>
        <div class="btn btn-large">
        <%= link_to recipe.name, recipe_path(recipe)%>
        </div>
        <%end%>
        <br>
        <div class="options">
        	<%= link_to 'Add a recipe', new_recipe_path %>
        	::
        	<%= link_to 'Add ingredients', new_ingredient_path %>
        </div>
  

<!--
<%= link_to 'Edit', edit_kitchen_path(@kitchen) %> |
<%= link_to 'Back', kitchens_path %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinnertyme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="row">
      <div class="span12">
        
        <div class="navbar">
          <div class="navbar-inner">
            <a class="brand" href="<%= home_path %>">DinnerTyme</a>
            <ul class="nav">
              <%= link_to 'Kitchens', kitchens_path %>
              <%= link_to 'Ingredients', ingredients_path %>
              <%= link_to 'Recipes', recipes_path %>
            </ul>
          </div>
        </div>
        
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <%=image_tag "fork-knife.jpg"%>
      </div>
      <div class="span9">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :kitchen_id %><br />
    <%= f.select :kitchen_id, Kitchen.all.map{|k|[k.name, k.id]}, {:prompt => "Pick a Kitchen"} %>
  </div>

  <div class="field">
    <% Ingredient.all.each do |ingredient| %>
      <%= ingredient.name %>
      <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, @recipe.ingredients.include?(ingredient) %>
      <%end%>
  </div>

  <div class="field">
    <%= f.label :steps %><br />
    <%= f.text_field :steps %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :serves %><br />
    <%= f.number_field :serves %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>My recipes</h1>



<% @recipes.each do |recipe| %>
  
    <h2><%= recipe.name %></h2>
    <h4>Steps:</h4>
    <p><%= recipe.steps %></p>
    <div class="recipe-image"><%= image_tag(recipe.photo) %></div>
    <div class="serves">Serves: <%= recipe.serves %></div>
    <div class="rating">Rating (out of 5): <%= recipe.rating %></div>
    <div class="managers"><%= link_to 'Show', recipe %></div>
    <div class="managers"><%= link_to 'Edit', edit_recipe_path(recipe) %></div>
    <div class="managers"><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></div>

<% end %>


<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<b>Kitchen:</b>
  <%= @recipe.kitchen.name %>
</p>

<p>
  <b>Steps:</b>
  <%= @recipe.steps %>
</p>

<p>
    <b>Ingredients</b>
    <% @recipe.ingredients.all.each do |ingredient| %>
    <li><%= ingredient.name %></li>
    <%end%>

<p>
  <b>Photo:</b>
  <div class="recipe-image"><%= image_tag @recipe.photo %></div>
</p>

<p>
  <b>Serves:</b>
  <%= @recipe.serves %>
</p>

<p>
  <b>Rating:</b>
  <%= @recipe.rating %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>